engines:
  duplication:
    enabled: true
  eslint:
    enabled: true
    config:
      extensions:
      - .es6
      - .js
      - .jsx
ratings:
  paths:
  - app/**
  - src/**
exclude_paths:
- node_modules/**/*
