/**
 * @overview
 *
 * @since 0.1.0
 */
import { Map, OrderedMap } from 'immutable';

export const ApiEvents = Map({
  INITIALIZE_GAME: 'INITIALIZE_GAME',
  GET_PLAYER_BASE_DATA: 'GET_PLAYER_BASE_DATA',
  GET_PROFILE_DATA: 'GET_PROFILE_DATA',
  GET_FURNITURE: 'GET_FURNITURE',
  GET_BASE_DATA: 'GET_BASE_DATA',
  GET_MATERIAL: 'GET_MATERIAL',
  GET_USABLE_ITEMS: 'GET_USABLE_ITEMS',
  GET_FLEET_DATA: 'GET_FLEET_DATA',
  GET_FLEET: 'GET_FLEET',
  GET_SLOT_ITEMS: 'GET_SLOT_ITEMS',
  USE_ITEM: 'USE_ITEM',
  DESTROY_ITEM: 'DESTROY_ITEM',
  LOCK_EQUIPMENT: 'LOCK_EQUIPMENT',

  // Ship-related
  GET_CONSTRUCTION_DOCKS: 'GET_CONSTRUCTION_DOCKS',
  CRAFT_SHIP: 'CRAFT_SHIP',
  CHANGE_SHIP: 'CHANGE_SHIP',
  RESUPPLY_SHIP: 'RESUPPLY_SHIP',
  SCRAP_SHIP: 'SCRAP_SHIP',
  REMODEL_SHIP: 'REMODEL_SHIP',
  MODERNIZE_SHIP: 'MODERNIZE_SHIP',

  // Equipment
  CRAFT_ITEM: 'CRAFT_ITEM',

  // Fleet-related (and combined)
  FLEET_COMBINED: 'FLEET_COMBINED',
  COMBINED_BATTLE_WATER_PHASE: 'COMBINED_BATTLE_WATER_PHASE',
  LOAD_FLEET_PRESET: 'LOAD_FLEET_PRESET',

  // Quests
  GET_QUEST_LIST: 'GET_QUEST_LIST',
  START_QUEST: 'START_QUEST',
  STOP_QUEST: 'STOP_QUEST',
  COMPLETE_QUEST: 'COMPLETE_QUEST',

  // Expeditions/missions
  GET_MISSION_LIST: 'GET_MISSION_LIST',
  START_MISSION: 'START_MISSION',
  QUIT_MISSION: 'QUIT_MISSION',
  COMPLETE_MISSION: 'COMPLETE_MISSION',

  // PVP/Practice
  GET_OPPONENT_INFO: 'GET_OPPONENT_INFO',
  GET_PVP_OPPONENT_LIST: 'GET_PVP_OPPONENT_LIST',
  START_PVP_BATTLE: 'START_PVP_BATTLE',
  START_PVP_NIGHT_BATTLE: 'START_PVP_NIGHT_BATTLE',
  FINISHED_PRACTICE: 'FINISHED_PRACTICE',

  // Sorties
  START_SORTIE: 'START_SORTIE',
  FINISHED_SORTIE: 'FINISHED_SORTIE',

  // Items
  USE_PAID_ITEM: 'USE_PAID_ITEM'
});

export const ApiEventPaths = OrderedMap({
  [ApiEvents.INITIALIZE_GAME]: '/api_start2',
  [ApiEvents.GET_BASE_DATA]: '/api_port/port',
  [ApiEvents.GET_FLEET]: '/api_get_member/ship_deck'
});

export const GameStates = Map({
  UNINITIALIZED: 'UNINITIALIZED',
  STARTING_GAME: 'STARTING_GAME',
  IN_SORTIE: 'IN_SORTIE',
  IN_PRACTICE: 'IN_PRACTICE',
  IDLE: 'IDLE',
  FINISHED_PRACTICE: 'FINISHED_PRACTICE',
  BROWSING_MISSIONS: 'BROWSING_MISSIONS',
  MISSION_STARTED: 'MISSION_STARTED'
});
