/**
 * @overview
 *  Constants shared between main- and renderer process
 *
 * @since 0.1.0
 */
export default {
  TIMER_START: 'TIMER_START',
  TIMER_STARTED: 'TIMER_START_ACK',
  TIMER_SYNC: 'TIMER_SYNC',
  TIMER_STOP: 'TIMER_STOP',
  TIMER_CLEAR: 'TIMER_CLEAR',
  TIMER_CLEAR_ALL: 'TIMER_CLEAR_ALL',
  TIMER_CLEARED_ALL: 'TIMER_CLEARED_ALL',
  TIMER_DONE: 'TIMER_DONE',
  TIMER_ERROR: 'TIMER_ERROR',
  DB_LOG_EVENT: 'DB_LOG_EVENT',
  REHYDRATE_STORE_REQUEST: 'REHYDRATE_STORE_REQUEST',
  REHYDRATE_STORE: 'REHYDRATE_STORE',
  DEHYDRATE_STORE: 'DEHYDRATE_STORE'
};
